name: Build and Test
on: push
jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        java-version: [ 17 ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: temurin
      - name: Cache Maven artifacts
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build ${{ matrix.java-version }}
        run: mvn -B clean test
        # we use public instances of nominatim and photon for testing
        env:
          NOM_EMAIL: ${{secrets.NOM_EMAIL}}
          OCD_KEY: ${{secrets.OCD_KEY}}
          PELIAS_URL: ${{secrets.PELIAS_URL}}
          PELIAS_KEY: ${{secrets.PELIAS_KEY}}
          NTK_KEY: ${{secrets.NTK_KEY}}
          GIS_GEO_URL: ${{secrets.GIS_GEO_URL}}
          GIS_REV_GEO_URL: ${{secrets.GIS_REV_GEO_URL}}
          GIS_SEARCH_URL: ${{secrets.GIS_SEARCH_URL}}
          GIS_KEY: ${{secrets.GIS_KEY}}
